variables:
  data_local: /leonardo_scratch/fast/IscrB_medit/training/minerva-7B-900B_it-900B_en-200B-code-21052024/data/processed
  # data_local: /leonardo/home/userexternal/lcolosi0/test-tokenizer-data
  # data_local: /leonardo_scratch/fast/mnrv_bblscp/minerva_pretraining/data/processed/tokenizer-51200
  data_remote: # If blank, files must be present in data_local
  max_seq_len: 4096 #16384 #2048  #2048
  global_seed: 17
  # run_name: minerva-replica-350m-900B_it-900B_en-200B-code
  run_name: minerva-replica-350M-data-2T-vocab-50k
  rank: 0
# If left blank, will be read from env var $RUN_NAME
max_seq_len: ${variables.max_seq_len}
run_name: ${variables.run_name}

# Model
model:
  use_auth_token: true
  # token: true
  name: hf_causal_lm
  use_flash_attention_2: true
  pretrained_model_name_or_path: mistralai/Mistral-7B-v0.1
  config_overrides:
    attention_dropout: 0.0
    bos_token_id: 1
    eos_token_id: 2
    hidden_act: silu
    hidden_size: 1152
    initializer_range: 0.02
    intermediate_size: 4032
    max_position_embeddings: 16384
    model_type: mistral
    num_attention_heads: 16
    num_hidden_layers: 16
    num_key_value_heads: 4
    rms_norm_eps: 1e-05
    rope_theta: 10000.0
    sliding_window: 2048
    tie_word_embeddings: false
    torch_dtype: bfloat16
    transformers_version: 4.38.2
    use_cache: false
    vocab_size: 51200 # vocab size of 7B model #32768
    # max_position_embeddings: 16384 # max_seq_len * 4    sliding_window: ${max_seq_len}

  pretrained: False

# Tokenizer
tokenizer:
  name: sapienzanlp/Minerva-7B-base-v1.0
  # name: local cache
  kwargs:
    # model_max_length: 1000000000000000019884624838656 # infinity model_max_length: ${max_seq_len}
    model_max_length: ${variables.max_seq_len} # infinitymodel_max_length: ${max_seq_len}
    use_fast: true

# Dataloaders
train_loader:
  name: text
  drop_last: true
  num_workers: 8
  dataset:
    predownload: 16384 # 8 * batch size
    shuffle: True
    num_canonical_nodes: 8
    shuffle_block_size: 262144
    # local: ${data_local}
    # split: en
    # shuffle_algo: py1b
    shuffle_seed: ${variables.global_seed}
    max_seq_len: ${variables.max_seq_len}
    streams:
      # it web
      it_culturax:
        local: ${variables.data_local}/it/culturax-filtered
        # local: ${variables.data_local}
        split: train
        repeat: 1.5
      it_redpajama_head:
        local: ${variables.data_local}/it/redpajama-head
        split: train
        repeat: 1.3
      it_redpajama_middle:
        local: ${variables.data_local}/it/redpajama-middle
        split: train
      # it hq
      it_wikipedia:
        local: ${variables.data_local}/it/wikipedia_it
        split: train
      it_books:
        local: ${variables.data_local}/it/books_it
        split: train
        repeat: 2.0
      it_eurlex:
        local: ${variables.data_local}/it/eurlex_it
        split: train
      it_gazzetta:
        local: ${variables.data_local}/it/gazetta
        split: train

      # en web
      en_fineweb_cc202410:
        local: ${variables.data_local}/en/fineweb/CC-MAIN-2024-10
        split: train
      en_fineweb_cc202350:
        local: ${variables.data_local}/en/fineweb/CC-MAIN-2023-50
        split: train
      en_fineweb_cc202340:
        local: ${variables.data_local}/en/fineweb/CC-MAIN-2023-40
        split: train
      en_fineweb_cc202323:
        local: ${variables.data_local}/en/fineweb/CC-MAIN-2023-23
        split: train
      en_fineweb_cc202314:
        local: ${variables.data_local}/en/fineweb/CC-MAIN-2023-14
        split: train

      # en hq
      en_arxiv_1:
        local: ${variables.data_local}/en/arxiv/part1
        split: train
      en_arxiv_2:
        local: ${variables.data_local}/en/arxiv/part2
        split: train
      en_arxiv_3:
        local: ${variables.data_local}/en/arxiv/part3
        split: train
      en_arxiv_4:
        local: ${variables.data_local}/en/arxiv/part4
        split: train
      en_stackexchange:
        local: ${variables.data_local}/en/stackexchange
        split: train
      en_wikipedia:
        local: ${variables.data_local}/en/wikipedia_en
        split: train
      en_books:
        local: ${variables.data_local}/en/gutenberg_en
        split: train

      # code
      code_part_1:
        local: ${variables.data_local}/code/starcoder2
        split: train
      code_part_2:
        local: ${variables.data_local}/code/starcoder2_part2
        split: train

# Optimization
#
# scheduler:
#   name: constant
#   lr: 1.0e-3
# # t_warmup: 2000ba #  llama2 uses 2000 steps
# # alpha_f: 0.1
#
# scheduler:
#   name: none

scheduler:
  name: cosine_with_warmup
  t_warmup: 1ba #  llama2 uses 2000 steps --> now using a single ba to speed up vocab adaptation
  alpha_f: 0.1
# scheduler:
#   name: constant_with_warmup
#   t_warmup: 1ba

optimizer:
  name: decoupled_adamw
  lr: 1.0e-3
  # betas:
  #   - 0.9
  #   - 0.95
  # eps: 1.0e-08
  weight_decay: 0.0

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

# max_duration = num_tokens / (max_seq_len * global_train_batch_size)
# ~2T tokens = max_seq_len * global_train_batch_size * max_duration
# ~2T is 2481170561843
# max duration is then 2481170561843 / (4096 * 1024) = 591_558
# max_duration: 591558ba
max_duration: 1ba
# eval_interval: 1000ba
eval_interval: 0
eval_first: false
eval_subset_num_batches: -1
global_train_batch_size: 1024

# System
seed: ${variables.global_seed}
device_eval_batch_size: 16
device_train_microbatch_size: 4
# device_train_microbatch_size: auto
precision: amp_bf16
# precision: fp32 # for debugging in cpu

# FSDP
fsdp_config:
  sharding_strategy: FULL_SHARD
  #sharding_strategy: HYBRID_SHARD
  mixed_precision: PURE
  activation_checkpointing: false
  #activation_checkpointing: false
  activation_checkpointing_reentrant: false
  activation_cpu_offload: false
  limit_all_gathers: true

# DeepSpeed
# deepspeed_config:
#   train_batch_size: 2048
#   train_micro_batch_size_per_gpu: 8
#   gradient_accumulation_steps: 8       # 2048/8/32 = 8 micro_batch_per_gpu * gradient_acc_step * world_size
#   bfloat16:
#     enabled: True
#   zero_optimization:
#     stage: 3

# Logging
progress_bar: true
log_to_console: true
console_log_interval: 100ba

callbacks:
  # optimizer_monitor:
  #   log_optimizer_metrics: true
  speed_monitor:
    window_size: 10
  lr_monitor: {}
  memory_monitor: {}
  runtime_estimator: {}

  hf_checkpointer:
    overwrite: true
    precision: bfloat16
    save_folder: /leonardo_scratch/large/userexternal/lcolosi0/minerva/replica/huggingface-cpt/${variables.run_name}
    save_interval: 500ba

loggers:
  wandb:
    entity: "leonardo-colosi"
    project: "minerva-llms-replica-350m"
    init_kwargs:
      mode: "offline"

# Checkpoint to local filesystem or remote object store
save_interval: 500ba
save_num_checkpoints_to_keep: -1 # Important, this cleans up checkpoints saved to DISK
save_folder: /leonardo_scratch/large/userexternal/lcolosi0/minerva/replica/runs/${variables.run_name}

# Uncomment this line to load a checkpoint
# load_path: /leonardo_scratch/large/userexternal/lcolosi0/minerva-pretraining/runs/${variables.run_name}/latest-rank${variables.rank}.pt
load_weights_only: False

autoresume: False # leave it to false, load_path is suficent to autoresume training

dist_timeout: 3600
